# Generated by Django 5.2.8 on 2026-01-06 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_date_of_birth_profile_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_new', to='users.role'),
        ),
    ]
