# Generated by Django 5.2.8 on 2026-01-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_role_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
