# Generated by Django 5.2.8 on 2026-02-13 14:33

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0010_alter_category_category_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(help_text='e.g., COMPX, LIPA', max_length=50, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True)),
                ('commission_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Percentage (e.g., 5.00 for 5%) or Fixed Amount', max_digits=5)),
                ('settlement_days', models.PositiveIntegerField(default=7, help_text='Days after customer confirmation to receive payment')),
                ('api_endpoint', models.URLField(blank=True)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CreditCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('county', models.CharField(max_length=100)),
                ('sub_county', models.CharField(blank=True, max_length=100)),
                ('location', models.TextField(blank=True)),
                ('partner_customer_id', models.CharField(blank=True, help_text="Customer ID in Company X's system", max_length=200)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum credit allowed by partner', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('credit_partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='credit_financing.creditpartner')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('credit_partner', 'partner_customer_id')},
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('phone_price', models.DecimalField(decimal_places=2, help_text="Price you'll receive from Company X", max_digits=12)),
                ('customer_total', models.DecimalField(decimal_places=2, help_text='Total amount customer pays to Company X (including interest)', max_digits=12)),
                ('partner_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission Company X charges', max_digits=12)),
                ('installment_amount', models.DecimalField(decimal_places=2, help_text='Monthly installment customer pays', max_digits=10)),
                ('installment_period', models.PositiveIntegerField(help_text='Number of months/installments')),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed by Partner'), ('active', 'Active - Customer Paying'), ('settled', 'Settled - You Paid'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmation_date', models.DateTimeField(blank=True, help_text='When Company X confirmed customer took phone', null=True)),
                ('expected_settlement_date', models.DateField(blank=True, help_text='When you expect payment from Company X', null=True)),
                ('actual_settlement_date', models.DateField(blank=True, help_text='When Company X actually paid you', null=True)),
                ('partner_reference', models.CharField(blank=True, help_text="Company X's transaction reference", max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='credit_financing.creditpartner')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='credit_financing.creditcustomer')),
                ('dealer', models.ForeignKey(help_text='You (the dealer)', on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='inventory.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('confirmed', 'Confirmed'), ('settled', 'Settled'), ('cancelled', 'Cancelled'), ('updated', 'Updated')], max_length=50)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('credit_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='credit_financing.credittransaction')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CustomerInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(help_text='1st, 2nd, 3rd installment, etc.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('late', 'Late'), ('missed', 'Missed')], default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='credit_financing.credittransaction')),
            ],
            options={
                'ordering': ['installment_number'],
            },
        ),
        migrations.CreateModel(
            name='DealerSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_id', models.CharField(max_length=100, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount Company X paid you', max_digits=12)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('mpesa', 'M-Pesa'), ('cheque', 'Cheque')], max_length=50)),
                ('payment_reference', models.CharField(max_length=200)),
                ('payment_date', models.DateField()),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='credit_financing.creditpartner')),
                ('transactions', models.ManyToManyField(related_name='settlements', to='credit_financing.credittransaction')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['transaction_id'], name='credit_fina_transac_81536c_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['status', '-created_at'], name='credit_fina_status_35ce0c_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['credit_partner', 'status'], name='credit_fina_credit__1dde70_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customerinstallment',
            unique_together={('credit_transaction', 'installment_number')},
        ),
    ]
