# Generated by Django 5.2.8 on 2026-02-14 11:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0010_alter_category_category_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(help_text='Company email for communication', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('code', models.CharField(blank=True, help_text='Auto-generated if left blank', max_length=50, unique=True)),
                ('address', models.TextField(blank=True)),
                ('payment_terms', models.CharField(blank=True, help_text='e.g., Net 30, Net 45, Weekly on Friday', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Company',
                'verbose_name_plural': 'Credit Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CreditCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('alternate_phone', models.CharField(blank=True, max_length=20)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('physical_address', models.TextField(blank=True)),
                ('nok_name', models.CharField(blank=True, max_length=200)),
                ('nok_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('product_code', models.CharField(blank=True, max_length=100)),
                ('imei', models.CharField(blank=True, help_text='Phone IMEI number (if applicable)', max_length=100)),
                ('ceiling_price', models.DecimalField(decimal_places=2, help_text='Amount the credit company will pay you', max_digits=12)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_date', models.DateTimeField(blank=True, help_text='When the company paid you', null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid by Company'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text="Company's payment reference (M-Pesa code, bank ref, etc.)", max_length=200)),
                ('company_reference', models.CharField(blank=True, help_text='Reference number from the credit company', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_company', models.ForeignKey(help_text='Select the credit company', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='credit_financing.creditcompany')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='credit_financing.creditcustomer')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='inventory.product')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='CompanyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount paid', max_digits=12)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('cash', 'Cash')], max_length=20)),
                ('payment_reference', models.CharField(help_text='M-Pesa code, bank reference, cheque number, etc.', max_length=200)),
                ('payment_date', models.DateField()),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
                ('credit_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='credit_financing.creditcompany')),
                ('transactions', models.ManyToManyField(related_name='company_payments', to='credit_financing.credittransaction')),
            ],
            options={
                'verbose_name': 'Company Payment',
                'verbose_name_plural': 'Company Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Transaction Created'), ('paid', 'Paid by Company'), ('cancelled', 'Cancelled'), ('updated', 'Updated')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='credit_financing.credittransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='creditcustomer',
            index=models.Index(fields=['id_number'], name='credit_fina_id_numb_c578ea_idx'),
        ),
        migrations.AddIndex(
            model_name='creditcustomer',
            index=models.Index(fields=['phone_number'], name='credit_fina_phone_n_d60804_idx'),
        ),
        migrations.AddIndex(
            model_name='creditcustomer',
            index=models.Index(fields=['full_name'], name='credit_fina_full_na_9d335d_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['transaction_id'], name='credit_fina_transac_81536c_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['payment_status'], name='credit_fina_payment_2311ad_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['credit_company', 'payment_status'], name='credit_fina_credit__027b4e_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['-transaction_date'], name='credit_fina_transac_5e7fe7_idx'),
        ),
    ]
