# Generated by Django 5.2.8 on 2026-02-14 23:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_financing', '0001_initial'),
        ('inventory', '0010_alter_category_category_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='etr_receipt_number',
            field=models.CharField(blank=True, help_text='ETR receipt number (e.g., 0501)', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['etr_receipt_number'], name='credit_fina_etr_rec_24e532_idx'),
        ),
    ]
