# Generated by Django 5.2.8 on 2026-01-31 19:16

import django.db.models.deletion
import django.utils.timezone
import staff_registration.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffapplication',
            options={'ordering': ['-application_date'], 'verbose_name': 'Staff Application', 'verbose_name_plural': 'Staff Applications'},
        ),
        migrations.RenameField(
            model_name='staffapplication',
            old_name='notes',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='staffapplication',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='staffapplication',
            old_name='position_applied',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='staffapplication',
            old_name='is_processed',
            new_name='privacy_accepted',
        ),
        migrations.RenameField(
            model_name='staffapplication',
            old_name='approval_date',
            new_name='review_date',
        ),
        migrations.RenameField(
            model_name='staffapplication',
            old_name='qualifications',
            new_name='review_notes',
        ),
        migrations.RenameField(
            model_name='staffapplication',
            old_name='rejection_reason',
            new_name='user_agent',
        ),
        migrations.RemoveField(
            model_name='staffapplication',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='staffapplication',
            name='registration_date',
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='application_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='id_back',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=staff_registration.models.id_back_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='id_front',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=staff_registration.models.id_front_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='id_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='passport_photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=staff_registration.models.passport_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='position',
            field=models.CharField(choices=[('sales_assistant', 'Sales Assistant'), ('cashier', 'Cashier'), ('store_manager', 'Store Manager'), ('inventory_clerk', 'Inventory Clerk'), ('customer_service', 'Customer Service Representative'), ('supervisor', 'Supervisor'), ('assistant_manager', 'Assistant Manager'), ('security', 'Security Officer'), ('cleaner', 'Cleaner')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='pending', max_length=20),
        ),
    ]
