# Generated by Django 5.2.8 on 2026-02-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_registration', '0003_staffapplication_created_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffapplication',
            name='position',
            field=models.CharField(choices=[('sales_assistant', 'Sales Officer'), ('cashier', 'Cashier Desk'), ('store_manager', 'Store Manager'), ('inventory_clerk', 'Inventory Clerk'), ('customer_service', 'Customer Care Service '), ('supervisor', 'Supervisor'), ('assistant_manager', 'Sales Manager'), ('security', 'Security Officer'), ('cleaner', 'Office Cleaner')], max_length=50),
        ),
    ]
