# Generated by Django 5.2.8 on 2026-01-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_supplier_product_brand_product_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Barcode for bulk items', max_length=200, null=True),
        ),
    ]
