# Generated by Django 5.2.8 on 2026-01-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
