# Generated by Django 5.2.8 on 2025-12-12 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_amount_paid_sale_batch_id_sale_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='sales.saleitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale'),
        ),
    ]
