# Generated by Django 5.2.8 on 2026-02-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20251213_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('M-Pesa', 'M-Pesa'), ('Card', 'Card'), ('Points', 'Points')], default='Cash', max_length=20),
        ),
    ]
